---
name: Test Workflow
on:
  workflow_dispatch:
  
jobs:

  ci:
    name: CI Job
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout Code from Git Repo
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
    
     
      - name: Echo
        run: |
         val = 'test'
         echo $val
         
         gh set variable TestVariable -b 'TestVariableValue'
