---
name: Test Workflow
on:
  workflow_dispatch:
  
jobs:

  ci:
    name: CI Job
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout Code from Git Repo
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
    
     
      - name: Echo
        run: |
          if ${var1} == 'test'; then
            echo "var2=testvar2" >> $GITHUB_ENV
            echo $var2
          else
            echo "var2=nottest" >> $GITHUB_ENV
            echo $var2
          fi         
          gh variable set TestVariable -b 'TestVariableValue'
        env:
          var1: 'test'
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
